name: Test Package

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    
    - name: Install dependencies
      run: |
        uv sync --dev
    
    - name: Build package
      run: |
        uv build
    
    - name: Test package import
      run: |
        python -c "import gsheet_mcp_server; print('✅ Package imports successfully')"
    
    - name: Check package contents
      run: |
        python -c "import tarfile; t = tarfile.open('dist/google_sheets_mcp-0.1.0.tar.gz'); print(f'Package contains {len(t.getmembers())} files')"
